import 'package:risk_radar/model/disaster_model.dart';
import 'package:risk_radar/utils/image_constants.dart';
import 'package:stacked/stacked.dart';

class DisastersViewModel extends BaseViewModel {
  List<DisasterModel> disasters = [
    DisasterModel(
        id: 1,
        location: "The Geysers, CA",
        locationDetail: "3 miles WNW of The Geysers, CA",
        countryImage: ImageConstants.americaFlag,
        date: "Mar 4 2023, 17:45:29",
        agotime: "54 mins",
        magnitude: 1.28,
        radius: 124026,
        depth: 4.0,
        lat: 37.45,
        lng: 121.744),
    DisasterModel(
        id: 2,
        location: "Hatay, Turkey",
        locationDetail: "Hatay",
        countryImage: ImageConstants.turkeyFlag,
        date: "Mar 4 2023, 17:45:29",
        agotime: "10 mins",
        magnitude: 1.80,
        radius: 124026,
        depth: 4.0,
        lat: 37.45,
        lng: 121.744),
    DisasterModel(
        id: 3,
        location: "Kahrammanmaras, Turkey",
        locationDetail: "Eastern Turkey",
        countryImage: ImageConstants.turkeyFlag,
        date: "Mar 4 2023, 17:45:29",
        agotime: "10 mins",
        magnitude: 1.60,
        radius: 124026,
        depth: 4.0,
        lat: 37.45,
        lng: 121.744),
    DisasterModel(
        id: 3,
        location: "West Sumatra, Indonesia",
        locationDetail: "Kep. Mentawai Region, Indonesia",
        countryImage: ImageConstants.indonesiaFlag,
        date: "Mar 4 2023, 17:45:29",
        agotime: "1 hr",
        magnitude: 4.20,
        radius: 124026,
        depth: 4.0,
        lat: 37.45,
        lng: 121.744),
    DisasterModel(
        id: 1,
        location: "The Geysers, CA",
        locationDetail: "3 miles WNW of The Geysers, CA",
        countryImage: ImageConstants.americaFlag,
        date: "Mar 4 2023, 17:45:29",
        agotime: "54 mins",
        magnitude: 1.28,
        radius: 124026,
        depth: 4.0,
        lat: 37.45,
        lng: 121.744),
    DisasterModel(
        id: 2,
        location: "Hatay, Turkey",
        locationDetail: "Hatay",
        countryImage: ImageConstants.turkeyFlag,
        date: "Mar 4 2023, 17:45:29",
        agotime: "10 mins",
        magnitude: 1.80,
        radius: 124026,
        depth: 4.0,
        lat: 37.45,
        lng: 121.744),
    DisasterModel(
        id: 3,
        location: "Kahrammanmaras, Turkey",
        locationDetail: "Eastern Turkey",
        countryImage: ImageConstants.turkeyFlag,
        date: "Mar 4 2023, 17:45:29",
        agotime: "10 mins",
        magnitude: 1.60,
        radius: 124026,
        depth: 4.0,
        lat: 37.45,
        lng: 121.744),
    DisasterModel(
        id: 3,
        location: "West Sumatra, Indonesia",
        locationDetail: "Kep. Mentawai Region, Indonesia",
        countryImage: ImageConstants.indonesiaFlag,
        date: "Mar 4 2023, 17:45:29",
        agotime: "1 hr",
        magnitude: 4.20,
        radius: 124026,
        depth: 4.0,
        lat: 37.45,
        lng: 121.744),
  ];
}
